# Generated by Django 4.2.26 on 2026-04-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='new_order',
        ),
    ]
