# Generated by Django 4.2.26 on 2026-04-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_rename_order_orderitem_new_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='_'),
        ),
    ]
