# Generated by Django 4.2.26 on 2026-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
