# Generated by Django 4.2.26 on 2026-04-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='first_name',
            new_name='fisrt_name',
        ),
    ]
