# Generated by Django 4.2.26 on 2026-06-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_rename_first_name_customers_fisrt_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['order_date']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='customers',
            name='fisrt_name',
        ),
        migrations.AddField(
            model_name='customers',
            name='first_name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
