# Generated by Django 4.2.26 on 2026-03-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.TextField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75)),
            ],
        ),
    ]
